HW2 is completed
diversantvlz/go-learn pull request #2
Opened 2022-12-02 16:47 UTC by diversantvlz

## Домашнее задание №2 «Распаковка строки»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [ ] Я сравнил объем кода с объемом авторского решения. [Зачем сверять объем кода?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D1%81%D0%B2%D0%B5%D1%80%D1%8F%D1%82%D1%8C-%D0%BE%D0%B1%D1%8A%D0%B5%D0%BC-%D0%BA%D0%BE%D0%B4%D0%B0)
  - unpack.go ~45 строк для задания без звездочки
  - unpack.go ~75 строк для задания со звездочкой

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2022-12-02 17:44 UTC, vladislavmass requested changes
Работа проходит все тесты и работает когда используются символы ASCII. Работа не проходит тесты с использованием например кириллицы. Как тест кейс можно использовать строку  a4bя2d5e

2022-12-06 16:06 UTC, diversantvlz commented
@vladislavmass исправил

2022-12-06 17:58 UTC, vladislavmass requested changes
Работа стала лучше. То, что обрабатываются ситуации когда число повторений равно нуля это прям здорово. В работу требуется внести несколько правок и будет прям отлично. И желательно что бы работа все таки поддерживала взаимодействие с ней через go get.

2022-12-06 17:58 UTC, vladislavmass commented on hw02_unpack_string/unpack.go
> +	runes := []rune(inputString)
Можно ли решить задачу без дополнительной аллокации памяти?

2022-12-06 17:58 UTC, hungry-honeybadger commented on hw02_unpack_string/unpack.go
> +		if runes[position] == 92 {
Непонятно что означает число 92. Лучше создать именованную константу и присвоить ей это значение. Таким образом человек читающий код поймет зачем нужно это число

2022-12-07 14:05 UTC, diversantvlz commented on hw02_unpack_string/unpack.go
> +		if runes[position] == 92 {
тут поправил

2022-12-07 14:08 UTC, diversantvlz commented on hw02_unpack_string/unpack.go
> +	runes := []rune(inputString)
Немного непонятно, вы намекаете на `for i,r := range(inputString)` ? Я тут еще наткнулся на https://pkg.go.dev/strings#Reader но это было уже после того как написал задачу.

2022-12-07 14:16 UTC, vladislavmass commented on hw02_unpack_string/unpack.go
> +	runes := []rune(inputString)
Да, именно на `for i,r := range(inputString)`.

2022-12-07 16:34 UTC, diversantvlz commented on hw02_unpack_string/unpack.go
> +	runes := []rune(inputString)
Я пробовал, не понял как курсор менять, это нужно для кейса с повторением равным 0, и для бекслешей

2022-12-07 17:04 UTC, vladislavmass commented on hw02_unpack_string/unpack.go
> +	runes := []rune(inputString)
Курсор менять нельзя и указывает он на первый байт символа, а не на символ.

2022-12-07 17:50 UTC, diversantvlz commented on hw02_unpack_string/unpack.go
> +	runes := []rune(inputString)
Я про это и говорю. Пробовал for i,r := range(inputString). как уложить там логику так и не разобрался, так как для реализации всех требований требуется перескакивать итерации и заглядывать вперед.

например мы в итерации получаем слеш, берем следующий символ, печатаем его и перескакиваем на 2 индекса, как это сделать в конструкции цикла range не знаю, если это возможно подскажите.

Следовательно тут либо range не подходит либо я делаю что-то не правильно

2022-12-07 18:00 UTC, vladislavmass commented on hw02_unpack_string/unpack.go
> +	runes := []rune(inputString)
Попробуйте смотреть не вперед, а назад.

2022-12-07 19:45 UTC, diversantvlz commented on hw02_unpack_string/unpack.go
> +	runes := []rune(inputString)
Пробовал. Проблемы с дабл слешеми, либо с нулевым репитом. 
вот эти кейсы я так и не победил 
```
{input: `qwe\\5`, expected: `qwe\\\\\`},
{input: `qwe\\\3`, expected: `qwe\3`},
```

Давайте так, я сделаю еще один подход если у вас есть готовая реализация которая реализует все задания включая дополнительные через `range` и в случае если у меня не получится вы сможете мне её показать, иначе если таковой нету, то предлагаю оставить как есть.

2022-12-08 14:14 UTC, vladislavmass commented on hw02_unpack_string/unpack.go
> +	runes := []rune(inputString)
В принципе на текущем этапе  я уже могу принять ребят на максимальный бал. Если хотите то, можете попробовать еще раз, я готов это проверить. Если вы хотите увидеть мое решение этой задачи, то я могу вам его показать после принятия работы.

2022-12-09 16:43 UTC, diversantvlz commented on hw02_unpack_string/unpack.go
> +	runes := []rune(inputString)
Да давайте оставим, да хочу посмотреть решение

2022-12-09 17:20 UTC, vladislavmass commented on hw02_unpack_string/unpack.go
> +	runes := []rune(inputString)
Хорошо. Тогда предлагаю сдать работу на повторную проверку.

2022-12-09 19:32 UTC, diversantvlz commented on hw02_unpack_string/unpack.go
> +	runes := []rune(inputString)
как это делать? еще раз ссылку на пр в чате отправить?

2022-12-09 19:44 UTC, vladislavmass commented on hw02_unpack_string/unpack.go
> +	runes := []rune(inputString)
Да.

2022-12-12 11:24 UTC, vladislavmass approved these changes
Работа принята. 10/10

2022-12-12 12:22 UTC, merged