Hw03 frequency analysis
diversantvlz/go-learn pull request #3
Opened 2022-12-06 17:17 UTC by diversantvlz

2022-12-06 18:19 UTC, vladislavmass requested changes
Алгоритм работы выбран правильно. Радует использование регекспов и реализация дополнительных заданий. В программе присутствует ошибка приводящая к панике. Новые юнит тесты не были добавлены. Модуль не может быть использован через go get.

Также в комит попали правки по 2 заданию.

2022-12-06 18:19 UTC, vladislavmass commented on hw03_frequency_analysis/top.go
> +	return keys[0:10]
Если в слайсе будет менее 10 слов, ты будет паника.

2022-12-07 14:50 UTC, diversantvlz commented
Поправил, кроме тестов, что за тесты в задании ничего не сказано?

2022-12-07 14:50 UTC, diversantvlz commented on hw03_frequency_analysis/top.go
> +	return keys[0:10]
поправил

2022-12-08 18:29 UTC, vladislavmass reviewed
В задание сказано добавить новые юнит тесты. За это дается 4 бала. Какие тесты добавить решать вам.

2022-12-09 16:44 UTC, diversantvlz commented
а, ок добавил кейс на строки меньше 10 и лексиграфическую сортировку

2022-12-13 07:55 UTC, vladislavmass approved these changes
Ошибки все исправлены. Работа принята. Оценка 10/10

2022-12-13 08:03 UTC, merged