Hw04 lru cache
diversantvlz/go-learn pull request #4
Opened 2022-12-09 16:05 UTC by diversantvlz

## Домашнее задание №4 «LRU-кэш»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [x] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [x] Я запустил `go mod tidy`.
- [x] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [x] Я проверил, что все операции выполняются за О(1).

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты для списка - 1 балл
- [ ] Добавлены новые юнит-тесты для кэша (включая тест на логику
выталкивания из кэша редко используемых элементов) - до 3 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2022-12-10 14:21 UTC, vladislavmass requested changes
Работа хорошая. Очень порадовало использование RWMutex. Кэш не работает как должен. Для обнаружения ошибки рекомендую добавить тест на обновление.

2022-12-10 14:21 UTC, hungry-honeybadger commented on hw04_lru_cache/list.go
> +	list  *list
Изначально реализованные структуры являются частью условия. Менять их не надо.

2022-12-10 14:21 UTC, hungry-honeybadger commented on hw04_lru_cache/go.mod
> +module github.com/diversantvlz/go-learn/tree/hw04_lru_cache
Неверное имя модуля. В нем явно что-то лишнее

2022-12-10 14:21 UTC, vladislavmass commented on hw04_lru_cache/list.go
> +	if nil != i.Prev {
Крайне непривычное написание. Обычное вначале пишут что сравнивают, а потом с чем сравнивают.

2022-12-10 14:21 UTC, vladislavmass commented on hw04_lru_cache/cache.go
> +	cache.items = map[Key]*ListItem{}
Если есть информация о максимальной количестве элементов в словаре, то лучше сразу выделить под них память.

2022-12-10 14:52 UTC, vladislavmass commented on hw04_lru_cache/list.go
> +	list  *list
К мьютексу это не относится так, как он нужен для дополнительного условия

2022-12-12 10:26 UTC, diversantvlz commented on hw04_lru_cache/list.go
> +	if nil != i.Prev {
это йода стаил https://ru.wikipedia.org/wiki/%D0%A3%D1%81%D0%BB%D0%BE%D0%B2%D0%B8%D1%8F_%D0%99%D0%BE%D0%B4%D1%8B
у нас в компании активно практикуется. Предлагаю не заморачиваться по вопросам код стайла, так как холиварная тема и в каждой компании может быть по разному.

2022-12-12 10:36 UTC, diversantvlz commented on hw04_lru_cache/list.go
> +	list  *list
Тогда вопрос как реализовать проверку элемента на принадлежность к списку в O(1) в методах Remove и MoveToFront или там допускается O(n)? в ДЗ есть такое условие, причем жирным выделено :)

2022-12-12 10:49 UTC, diversantvlz commented on hw04_lru_cache/go.mod
> +module github.com/diversantvlz/go-learn/tree/hw04_lru_cache
поправил

2022-12-12 10:50 UTC, diversantvlz commented on hw04_lru_cache/cache.go
> +	cache.items = map[Key]*ListItem{}
поправил

2022-12-12 11:06 UTC, vladislavmass commented on hw04_lru_cache/list.go
> +	list  *list
Считаем, что методы Remove и MoveToFront вызываются только от существующих в списке элементов.

2022-12-12 11:07 UTC, hungry-honeybadger commented on hw04_lru_cache/list.go
> +	if nil != i.Prev {
Ок.

2022-12-14 20:38 UTC, vladislavmass approved these changes
Работа принята. 10/10

2022-12-14 20:38 UTC, vladislavmass commented on hw04_lru_cache/cache.go
> +	for item := cache.queue.Front(); item != nil; item = item.Next {
Можно было бы конечно просто пересоздать list. Но это уже по желанию.

2022-12-15 10:13 UTC, merged