Hw05 parallel execution
diversantvlz/go-learn pull request #5
Opened 2022-12-13 10:37 UTC by diversantvlz

## Домашнее задание №5 «Параллельное исполнение»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [ ] Я сравнил объем кода с объемом авторского решения. [Зачем сверять объем кода?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D1%81%D0%B2%D0%B5%D1%80%D1%8F%D1%82%D1%8C-%D0%BE%D0%B1%D1%8A%D0%B5%D0%BC-%D0%BA%D0%BE%D0%B4%D0%B0)
  - run.go ~55 строк

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2022-12-14 12:22 UTC, dshemin requested changes

2022-12-14 12:22 UTC, dshemin commented on hw05_parallel_execution/run.go
> +	sync.RWMutex
Критично:

Не надо так делать. Мы даём возможность использовать методы мьютекса на нашей структуре внешним пользователям - это неверно.

2022-12-14 12:22 UTC, dshemin commented on hw05_parallel_execution/run.go
> +	sync.RWMutex
Совет:

Используйте sync.Mutex вместо sync.RWMutex. Мы используем только полный лок.

2022-12-14 12:22 UTC, dshemin commented on hw05_parallel_execution/run.go
> +	queue := Queue{tasks: tasks}
Критично:

Не очень эффективное решение. Более того - переизобретение каналов.

2022-12-15 00:30 UTC, dshemin requested changes

2022-12-15 00:30 UTC, dshemin commented on hw05_parallel_execution/run.go
> +	for _, task := range tasks {
Критично:

Смотрите, у нас получается следующее: у нас есть массив из n эллементов, мы выделяем память под ещё n эллементов, копируем их туда и потом обрабатываем. В итоге у нас n^2 потребления памяти. При условии что у нас может быть ситуация когда m = 1 и первая же таска возвращает ошибку ... не очень удачная картина. 

Советую пополнение канала делать в отдельной горутине.

2022-12-15 00:30 UTC, dshemin commented on hw05_parallel_execution/run.go
> +				select {
Важно:

Зачем такая сложность? Мы можем просто сделать так:
```
for task := range queue {
    ...
}
```

2022-12-15 08:48 UTC, diversantvlz commented on hw05_parallel_execution/run.go
> +	for _, task := range tasks {
Я поправил, но не понятно зачем нам отдельная горутина для паблиша в канал, у нас же Run все равно будет ждать. Т.е мы можем  объявить сначало горутины для чтения, а потом в цикле паблишить таски и получится тоже самое разве не так?

2023-01-25 06:08 UTC, dshemin approved these changes

2023-01-25 06:08 UTC, dshemin commented on hw05_parallel_execution/run.go
> +	for i := 0; i < n; i++ {
Важно:

Обработайте и напишите тест для случая когда n <= 0.

2023-01-25 06:22 UTC, merged